// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _6_webapi.Models;

#nullable disable

namespace _6_webapi.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("_6_webapi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 2000m,
                            ProductName = "Iphone 8"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 3000m,
                            ProductName = "Iphone 9"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            Price = 4000m,
                            ProductName = "Iphone 10"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 5000m,
                            ProductName = "Iphone 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
